### ISSUE TITLE
[ERROR] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ditchfieldcaleb** [lwYeo/SoliditySHA3Miner#1]
OS: Ubuntu 17.04 LTS
Setup: 4 x GTX 1060

Command: `./0xbtcPSolo.sh`

File Contents: 

```
#!/usr/bin/env bash

command -v dotnet >/dev/null 2>&1 ||
{
 echo >&2 ".NET Core is not found or not installed,"
 echo >&2 "download and install from https://www.microsoft.com/net/download/linux/run";
 read -p "Press any key to continue...";
 exit 1;
}
dotnet SoliditySHA3Miner.dll web3api=http://XXX.XXX.XXX.XXX:8545/ abiFile=0xbtc.abi contract=0xB6eD7644C69416d67B522e20bC294A9a9B405B31 gasToMine=50 privateKey=XXXX
```

Error: "[ERROR] Object reference not set to an instance of an object."

This error seems to coincide with an info log every time right before it, saying "New difficulty detected (XXXXXXXX)..."

As far as I can tell, it *is* still mining, however.

**Comment by lwYeo** [comment]
Fix will be implemented in the next public release.
