### ISSUE TITLE
Multiple AMD GPUs detection issue

### ISSUE THREAD

**Issue by atomrigs** [lwYeo/SoliditySHA3Miner#13]
The miner works with a single AMD RX580 GPU well, but If I add multiple same kinds of GPUs, it does not detect other GPUs correctly and stops working.
miner version: 2.2.0

The exact same system with 6 AMD RX580 gpus works well with MVis-tokenminer.

**Comment by lwYeo** [comment]
@atomrigs are you able to provide the console logs regarding this issue?

**Comment by atomrigs** [comment]
==Log file ==

*** SoliditySHA3Miner 2.2.0 by lwYeo@github (2018) ***
*** Built with .NET Core 2.1.5 SDK, VC++ 2017, gcc 4.8.5, nVidia CUDA SDK 9.2 64-bits, and AMD APP SDK v3.0.130.135 (OpenCL)

Donation addresses:
ETH (or any ERC 20/918 tokens)	: 0x9172ff7884CEFED19327aDaCe9C470eF1796105c
BTC                             : 3GS5J5hcG6Qcu9xHWGmJaV5ftWLmZuR255
LTC                             : LbFkAto1qYt8RdTFHL871H4djendcHyCyB

[2019-02-05T14:04:43] [INFO] King making disabled.
[2019-02-05T14:04:43] [INFO] Primary pool specified, using http://mike.rs:8080
[2019-02-05T14:04:43] CUDA [INFO] Device not specified, default assign all CUDA devices.
[2019-02-05T14:04:43] CUDA [ERROR] CUDA driver version is insufficient for CUDA runtime version
[2019-02-05T14:04:43] CUDA [WARN] Device not found.
[2019-02-05T14:04:43] OpenCL [INFO] AMD APP device not specified, default assign all AMD APP devices.


== atiflash device info ==

C:\Users\user\Desktop\atiflash_284>atiflash -i

adapter bn dn fn dID       asic           flash      romsize test    bios p/n
======= == == == ==== =============== ============== ======= ==== ==============
   0    01 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100
   1    02 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100
   2    05 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100
   3    06 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100
   4    07 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100
   5    08 00 00 67DF Polaris10       GD25Q21B         40000 pass 113-D0003400_100


== sha3miner conf ==

{
  "isLogFile": false,
  "minerJsonAPI": "http://127.0.0.1:4078",
  "minerCcminerAPI": "127.0.0.1:4068",
  "web3api": "https://mainnet.infura.io/ANueYSYQTstCr2mFJjPE",
  "contractAddress": "0xB6eD7644C69416d67B522e20bC294A9a9B405B31",
  "abiFile": "0xBTC.abi",
  "overrideMaxTarget": "0x0",
  "customDifficulty": 0,
  "submitStale": false,
  "maxScanRetry": 3,
  "pauseOnFailedScans": 3,
  "networkUpdateInterval": 15000,
  "hashrateUpdateInterval": 30000,
  "masterMode": false,
  "masterURL": "",
  "slaveUpdateInterval": 5000,
  "kingAddress": "",
  "minerAddress": "0x91....",
  "primaryPool": "http://mike.rs:8080",
  "secondaryPool": "",
  "privateKey": "",
  "gasToMine": 3.0,
  "gasLimit": 1704624,
  "gasApiURL": "https://ethgasstation.info/json/ethgasAPI.json",
  "gasApiPath": "$.safeLow",
  "gasApiMultiplier": 0.1,
  "gasApiOffset": 0.5,
  "gasApiMax": 7.0,
  "allowCPU": false,
  "cpuDevice": {
    "Affinities": null,
    "AllowDevice": false,
    "Type": null,
    "Platform": null,
    "DeviceID": 0,
    "PciBusID": 0,
    "Name": null,
    "Intensity": 0.0
  },
  "allowIntel": true,
  "intelDevices": [],
  "allowAMD": true,
  "amdDevices": [],
  "allowCUDA": true,
  "cudaDevices": []
}

**Comment by lwYeo** [comment]
Another user reported a similar issue in 2.2.1.

**Comment by lwYeo** [comment]
Able to reproduce the following error with 1x RX 460 and 1x RX 570
```[2019-02-09T08:46:45] OpenCL (AMD APP) ID: 1 [ERROR] Failed to create context: CL_INVALID_DEVICE```
Then only the first AMD GPU starts to hash.

**Comment by lwYeo** [comment]
Tested version [2.2.2](https://github.com/lwYeo/SoliditySHA3Miner/releases/tag/2.2.2) in both Windows and HiveOS, running without issue on 1x RX570 and 1x RX460.
Pending other users with multiple similar cards to test. @atomrigs

**Comment by atomrigs** [comment]
> Tested version [2.2.2](https://github.com/lwYeo/SoliditySHA3Miner/releases/tag/2.2.2) in both Windows and HiveOS, running without issue on 1x RX570 and 1x RX460.
> Pending other users with multiple similar cards to test. @atomrigs

It works well with my 6 way RX 580 system now.
