### ISSUE TITLE
solo mining 

### ISSUE THREAD

**Issue by 0xGold** [lwYeo/SoliditySHA3Miner#3]
Any chance someone can get the solo mint function working properly on the 0xgold contract? I see that you have added the 0xGOLD.abi to the miner, but have not been able to achieve a mint ever since the merge mine function became active.
contract address: 0x291de53a16b76dfe28551fd3335225f506db8b82

**Comment by lwYeo** [comment]
Below is one of the failed solutions for reference:

Challenge: 0x887ed002705ef17658cb04584b2042f792f7a5c11a1bbced5fa62339e807a9a1
Address: 0xfd53570b7FD5Af2e89e822dB74636F99d16303E7
Solution: 0x11b14e86d6d315f5f4f12c894042640000000000c82be6cfa8a8ee857b8f2362
Digest: 0x0000036d39d7f356d12f0b6e87c7ed9433d23e9aa8107e5687be989716ad12cf
Target: 0x0000040000000000000000000000000000000000000000000000000000000000

 
We will need a dev who is able to determine 
the actual issue from the EVM assembly event error log. 
Note that there is no issue mining other tokens without merge mine function.

**Comment by lwYeo** [comment]
Seems that the issue has been fixed on the contract code side here https://github.com/snissn/0xlitecoin-token/commit/dfbe250bcc6b71d630fae2691ea934cc19dc20d1
Please redeploy 0xGold token contract using the above fix.
