### ISSUE TITLE
Missing the .exe?

### ISSUE THREAD

**Issue by BobbyGR** [lwYeo/SoliditySHA3Miner#4]
I was pretty sure this included the .exe in the .zip's.  it seems to be missing now?

**Comment by lwYeo** [comment]
From version 2.0.0 onwards, in order to achieve Linux compatibility, there is no more .exe executable.
To launch, enter "dotnet SoliditySHA3Miner.dll [args=value]"
The last version with .exe is in 1.3.0.0

**Comment by lwYeo** [comment]
With dotnet core 2.2 onwards, we are now able to publish the file as exe (without the enormous bootstrapping files)

**Comment by lwYeo** [comment]
exe file now available and able to launch in 2.2.1. Closing issue.
