### ISSUE TITLE
cpuID not working?

### ISSUE THREAD

**Issue by huglester** [lwYeo/SoliditySHA3Miner#5]
Hello, when using 
cpuID=0
cpuID=1,3,4 
or anything, I always get this error:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
./CLM.sh: line 16: 12381 Aborted                 dotnet SoliditySHA3Miner.dll abiFile=ERC-541.abi contract=xxxx pool=http://xxxxx address=yyyy cpuMode=true cpuID=0

**Comment by lwYeo** [comment]
Issue fixed in build db5d915efa051df4d2cdca46b0e59068fad25cbe
Please redownload the latest updated release. If you encountered any issue please reopen this issue.
